language: java

jdk:
  - openjdk8

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  # zip에 포함시킬 파일들을 담을 디렉터리 생성
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p depoy
  - mv before-deploy/before-deploy.zip deploy/springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot2-webserv-build
    region: ap-northeast-2
    skip_cleanup: true
    zcl: private #zip 파일 접근
    local_dir: deploy #before_deploy에서 생성
    wait-until-deployed: true

  - provider: codedeploy
    #Travis repo settings에 설정된 값
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    #S3버킷
    bucket: springboot2-webserv-build
    #빌드 파일 압축 전달, 압축 확장자
    key: springboot2-webservice.zip
    bundle_type: zip
    #웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    application: springboot2-webservice
    #배포그룹
    deployment_group: springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hori_q@naver.com